# Generated by Django 3.1.7 on 2021-03-12 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviesession_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='tickets_bought',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
