# Generated by Django 3.1.7 on 2021-03-12 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210312_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='tickets_bought',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
