# Generated by Django 3.1.7 on 2021-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movieticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticket',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
