# Generated by Django 3.1.7 on 2021-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210314_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='size',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
