# Generated by Django 3.1.7 on 2021-03-16 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20210314_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_day', models.DateField(default=django.utils.timezone.now)),
                ('end_day', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='name',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='start_day',
        ),
        migrations.AddField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
