# Generated by Django 3.1.7 on 2021-03-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20210316_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desciption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
