# Generated by Django 3.1.7 on 2021-03-18 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='sessions', to='movies.movie'),
        ),
    ]
