# Generated by Django 3.1.7 on 2021-03-24 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0020_auto_20210322_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='tickets_bought',
        ),
        migrations.AlterField(
            model_name='movieticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
